### ISSUE TITLE
Switch to pyproject.toml and poetry

### ISSUE THREAD

**Issue by c0fec0de** [c0fec0de/anytree#150]

**Comment by teauxfu** [comment]
I'd be willing to help out with this.

This could be a separate issue, but is this overwriting intentional?
https://github.com/c0fec0de/anytree/blob/d63289b65644c6e8c9c1d83d339c2c235d9ecc31/setup.py#L43-L49
Also @c0fec0de, how would you feel about including `graphiz` in the optional dependencies under `extras_require`?

**Comment by c0fec0de** [comment]
Done.
