### ISSUE TITLE
Performance test very slow

### ISSUE THREAD

**Issue by BR1py** [c0fec0de/anytree#169]
Hello,
I do some performance testing regarding tree structure related solutions in python.

The test code has the target to populate a tree with 50000 items and than to access each item one time per index and by name.

The results for anytree 2.8.0 (python 3.5) are very slow (related to other packages) and I like to ensure I did the right coding for it. Can you please review my code and give me a hint in case something can be done in a better way regarding the usage of anytree? 

```
    import timeit
    from anytree import Node, search

    max_items=50000 # number of items
    repeat = 4 # repetition number in timeit
    dt_root=None # global used to transfer the tree from one call to the next one

    print('We run for treesizes: %i with %i repetitions'%(max_items,repeat))

    print('-- anytree ---------------------------------')

    def performance_at_build():
        global dt_root, max_items,nodes
        dt = Node('root')
        for i in range(max_items):
            b=Node('%i' % i, parent=dt)
        dt_root = dt

    def performance_at_get_idx():
        global dt_root, max_items
        dt = dt_root
        for i in range(max_items):
            b = dt.children[i]

    def performance_at_get_key():
        global dt_root, max_items
        dt = dt_root
        for i in range(max_items):
            b = search.find(dt, lambda node: node.name == "%i" % i)

    a = timeit.timeit(performance_at_build, number=repeat)
    print('Exectime time Anytree build: {}'.format(a / repeat))
    a = timeit.timeit(performance_at_get_idx, number=repeat)
    print('Exectime time Anytree index access: {}'.format(a / repeat))
    a = timeit.timeit(performance_at_get_key, number=repeat)
    print('Exectime time Anytree key access (no cache): {}'.format(a / repeat))

```

If I execute this code I got the following results:

```
We run for treesizes: 50000 with 4 repetitions
-- anytree ---------------------------------
Exectime time Anytree build: 68.98334625
Exectime time Anytree index access: 11.958389874999995
```

I stopped the code here because the last calculation (item name search) takes hours!

Background: 
In my project I will have to build trees with up to 200000 elements. With the results I got for anytree it's so slow that it is unusable for my use-case.

Can you please give at least your opinion.

**Comment by c0fec0de** [comment]
Will have a look.

B.R. ***@***.***> schrieb am Di., 11. Mai 2021, 14:58:

**Comment by c0fec0de** [comment]
Hi,

thanks for opening this issue. First of all - anytree runs in pure python. There is no cpython backend. This is planned. But I simply had no time yet.

**`performance_at_build`**
The add operation runs some checks, which ensure a consistent tree at any state. The runtime depends on the tree depth. So you might not see the worst case here. Disabling or postponing the checks would improve the performance. I will think about a solution.

**`performance_at_get_idx`**
Here I see a potential optimization. I will give it a try.

**`performance_at_get_key`**
The bad performance is expected, as this is just a NP complete implementation. You are just iterating over all nodes every time without making any advance of the tree structure. In that use-case it is simpler to convert the entire tree into a tuple and search within this. If you order data in a tree, than make use of the tree structure and decide on every node on which child you want to continue your search.

Best
c0fec0de

**Comment by BR1py** [comment]
Hi,
thanks for the answer. I just wanted to be sure that I used the package correctly.
For your info:
I'm the author of [itertree](https://pypi.org/project/itertree/) and I published the results as a part of the documentation of the my package.
Best,
B.R.

**Comment by Paebbels** [comment]
I did some investigations on anytree and found these problems:

1. **API**
   * The API is using a top-down approach. This means, nodes need to be constructed from root to child nodes. There is no operation to add a child. It only allows to overwrite the whole list of children at once.
2. **Expensive Operations**
   * In many cases, internal data structures are converted forward and backward between lists and  tuples.  
     Examples:
     * Reading children returns a tuple.
     * Setting children, converts the input parameter to a tuple, which is then iterated.  
       Thus, no property of the tuple class is used except for being iterated over.
   * Disconnecting a child from a parent does a full list copy instead of an item removal.
   * Integrity check on every operation.  
     This could be solved with:
     * Optional checks on every operation.
     * Mass operations.
     * User controllable integrity check on the whole tree.
   * Property `__children_or_empty` adds an unnecessary function wrapper (getter property) around the internal field `__children`. This field is needed very often and shouldn't be slowed down by a property. There is actually no need for such a property, if the whole mixin would be properly initialized. The same applies to property `parent` and field `__parent`.
   * The computation if `path` is very in efficient.  
     `return tuple(reversed(list(self.iter_path_reverse())))`  
     This creates 3x a data structure:
     1. iterator to list conversion
     2. reversed list
     3. tuple from reversed list
     
     It could be solved e.g. with a DFS and returning items on the way up from root to the current node.
   * Access to the root is an often needed operation. This information should be kept as a direct pointer, but not been computed on every field access.
   * Getting the depth with `for i, _ in enumerate(self.iter_path_reverse())` is just funny. Sorry.  
     At first, `enumerate` should be used to avoid the overhead.  
     At second, a faster way could be: just a while loop to traverse upward until you find the root element.
3. **Other Internals**
   * Unnecessary `if parent is not None:` checks, because there is no possibility `parent` could be None, when the previous exception handler would be coded correctly...
   * `parent.__children_or_empty` is sometimes called multiple times in the same operation like in the property setter `parent`.
   * It's Python 2 code, but not yet Python 3 (only).
   * No typehints.
   * Usage of outdated string formatting syntax (using `%`).
   * The internal comments for `# ATOMIC START` and `# ATOMIC END` are wrong.  
     There are no groups of atomic operations in the code!
