### ISSUE TITLE
RenderTreeGraph Image Size

### ISSUE THREAD

**Issue by terryphi** [c0fec0de/anytree#17]
Hey,

My image output generated by RenderTreeGraph is looking a bit squished.

Any way to change the image size?

**Comment by terryphi** [comment]
http://imgur.com/a/I23rN

**Comment by c0fec0de** [comment]
Hi,

this is more a [Graphviz](http://www.graphviz.org/) issue rather than a anytree issue. Please see the graphviz documentation and feel free to improve the `RenderTreeGraph` implementation.

At the end, it is difficult to read a large graphic anyway. Did you consider splitting the graph or filtering it?
