### ISSUE TITLE
Plans to persist tree to file and create a tree from file?

### ISSUE THREAD

**Issue by ArgiesDario** [c0fec0de/anytree#30]
First of all, amazing work in here. I'm planing to use anytree to a huge kind of backtracking implementation. I will need to persist the tree to a file at some point, and of course, get the tree back from a file.

Are you planning to do it? Is it possible? Should i give it a try and then send the pull request?

Thank you

**Comment by KelSolaar** [comment]
@ArgiesDario : Have you tried to serialise the root node(s) with [pickle](https://docs.python.org/3.6/library/pickle.html)?

**Comment by c0fec0de** [comment]
Thanks. Pickling is one option. I will add tests for pickling, to ensure a consistent data structure.

Currently, i am implementing a dict/json import/export mechanism. JSON is a quite common format. Also used by other libraries. Human read- and writeable.

**Comment by c0fec0de** [comment]
XML Import/Export is also on my list...

Any preferences or other formats of interest here?

**Comment by ArgiesDario** [comment]
@KelSolaar It did not come to my mind at all, I give it a try and works like a charm. Ty :)

@c0fec0de A JSON import/export would be amazing, data will be readable and also its pretty easy to load it from somewhere else. XML also would be nice but not my favourite

I'll use pickle for now but when JSON import/export is implemented totally moving into that

Thanks both for interest on this an quick answers :)

**Comment by jkbgbr** [comment]
I usually use YAML to store data, IMHO it is more readable as JSON. Has great python support and - for me at least - feels very natural the way YAML stores and displays dictionaries.

**Comment by c0fec0de** [comment]
I try to complete it the next days and file a release...

**Comment by KelSolaar** [comment]
I have not put much thoughts into it yet but two things to consider:

- JSON objects are not ordered, so it might have some unattended side effects.
- Some people might be using `anytree.Node` or `anytree.NodeMixin` with potentially hard to dump/serialise classes, e.g. [QStandardItem](http://doc.qt.io/qt-4.8/qstandarditem.html), what would be the strategy for those?

**Comment by c0fec0de** [comment]
You can now make use of JSON and YAML

## YAML
PYYAML supports a lot of things. Wrapping is difficult. I do not want anytree to depend on pyyaml, to keep installation simple. Therefore is just added some example code to the documentation and tested it
http://anytree.readthedocs.io/en/latest/tricks/yaml.html
The import and export issues like node order and class creation are handled by [`DictImporter`](http://anytree.readthedocs.io/en/latest/importer/dictimporter.html) and [`DictExporter` ](http://anytree.readthedocs.io/en/latest/exporter/dictexporter.html)

## JSON 
JSON is natively supported by python. [`JsonImporter`](http://anytree.readthedocs.io/en/latest/importer/jsonimporter.html) an [`JsonExporter`](http://anytree.readthedocs.io/en/latest/exporter/jsonexporter.html) are included since version 2.3.0

**Comment by c0fec0de** [comment]
Please also take a look at http://anycache.readthedocs.io/en/latest/
It is designed to cache the loading of large data structures (like trees) via file system using an improved pickle.
